In [3]:
# Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements 
# using basic numpy functions.

import numpy as np
a = np.random.rand(10,1)
print(a)
print("Mean: ",a.mean())

[[0.76481573]
 [0.00509119]
 [0.69427426]
 [0.41043306]
 [0.6076562 ]
 [0.54875187]
 [0.74992776]
 [0.1160084 ]
 [0.28761072]
 [0.72855389]]
Mean:  0.49131230817110005


In [5]:
# Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation
# of the elements.
b = np.random.rand(20,1)
print(b)
print("Variance: ",b.var())
print("Standard Deviation: ",b.std())

[[0.85568996]
 [0.01441135]
 [0.04022212]
 [0.57797065]
 [0.21244574]
 [0.7001237 ]
 [0.86555414]
 [0.27673144]
 [0.53053372]
 [0.15302912]
 [0.9720737 ]
 [0.39152966]
 [0.21990571]
 [0.84310833]
 [0.48571823]
 [0.08823576]
 [0.99649994]
 [0.19340356]
 [0.70401466]
 [0.08887541]]
Variance:  0.10639164430112283
Standard Deviation:  0.32617732033530905


In [6]:
# Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the 
# matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only
# find the sum of all the elements of the new matrix.

In [7]:
A = np.random.rand(10,20)
print(A)

[[0.59352674 0.98230236 0.12708998 0.33396392 0.47532601 0.53778443
  0.90871366 0.79806148 0.30764629 0.80617342 0.86614058 0.39940999
  0.06924533 0.18173778 0.71135006 0.37848039 0.28134292 0.78380544
  0.1680365  0.55678704]
 [0.34149885 0.24771724 0.11406523 0.83386178 0.03144817 0.27290531
  0.87090159 0.55312216 0.13862852 0.001398   0.3567404  0.4627869
  0.95686804 0.63958238 0.90363276 0.82101774 0.70960602 0.13595938
  0.14506915 0.60047595]
 [0.88044616 0.16521287 0.46005723 0.19785729 0.23315459 0.71438222
  0.51690599 0.95153717 0.6723801  0.42838597 0.44838553 0.31565942
  0.50704842 0.73121501 0.43553565 0.02279653 0.08011331 0.3780458
  0.12382078 0.3154183 ]
 [0.67774402 0.13421949 0.82835095 0.22982034 0.90939156 0.63382726
  0.31054344 0.18701284 0.00257136 0.52147142 0.9361473  0.28221731
  0.94086627 0.5605369  0.04302648 0.7283407  0.22758455 0.78264034
  0.40256904 0.15056405]
 [0.74543166 0.8853686  0.70588049 0.64898353 0.62306594 0.35409563
  0.59982431 0.466

In [10]:
B = np.random.rand(20,25)
print(B)

[[0.0028581  0.62548911 0.26946059 0.8156696  0.31080963 0.77603629
  0.62181131 0.72792915 0.51832994 0.34657168 0.50877706 0.01712885
  0.86939299 0.77007688 0.74679927 0.12225607 0.25074338 0.81819926
  0.76115676 0.67939547 0.55455725 0.30155301 0.09445101 0.73243825
  0.01362259]
 [0.70891669 0.92116701 0.96751161 0.01568498 0.43997596 0.2321864
  0.7617439  0.44970654 0.87094082 0.22799773 0.52090731 0.98288724
  0.7978981  0.84883694 0.02608566 0.29771134 0.80696308 0.06847082
  0.57353948 0.79495921 0.64218996 0.46907126 0.63316513 0.02704034
  0.32594265]
 [0.55499392 0.6181352  0.0165245  0.35931182 0.53261556 0.11524708
  0.11504018 0.25792102 0.33680288 0.65730444 0.57901796 0.05514146
  0.72851145 0.22907682 0.07548689 0.40446013 0.20029052 0.20361771
  0.54493341 0.02310837 0.2228334  0.08965408 0.33505092 0.76174221
  0.08295549]
 [0.88199644 0.35560793 0.93919514 0.22860365 0.86548763 0.40350277
  0.76343694 0.41861423 0.95454686 0.32601208 0.69300799 0.93095339
  0.307

In [11]:
C = np.matmul(A,B)
print("Matrix Multiplication: ",C)

Matrix Multiplication:  [[5.18787355 5.54255759 5.23279332 3.87464972 4.82187669 4.99397867
  5.4823204  4.2249691  6.43509832 4.16081009 6.18391211 6.53110094
  4.99702651 5.91247423 6.2029327  3.82716865 6.79908754 4.87135817
  4.49307264 5.31924549 5.84597211 4.23364428 3.86994828 3.21117809
  5.36474173]
 [4.94840034 4.70975799 4.96829658 3.58765322 5.00845234 5.08073902
  5.74778881 2.94146233 5.19146388 3.76389679 5.48899095 5.90028841
  4.9760807  4.8707824  6.42210173 4.11255414 5.92133727 4.8225202
  3.9173415  4.42334367 5.23360811 3.25676146 3.68799759 2.430732
  4.29994304]
 [3.96237968 4.10880383 3.80353972 3.52892994 4.01364449 4.23120069
  4.53283782 4.05058041 4.47574773 3.58565964 4.60724552 4.6529457
  4.80382439 4.3268987  5.99547028 3.03920836 5.3661716  4.057883
  3.81978764 4.08766598 4.61174276 3.0702235  2.79283483 3.13127482
  3.95652918]
 [4.98982223 5.10940024 4.597824   3.88942655 4.83048369 4.23666133
  5.28422627 3.45706796 5.58305438 3.79508931 5.22163915

In [12]:
C.shape

(10, 25)

In [13]:
print("Sum of elements of new array is: ",np.sum(C))

Sum of elements of new array is:  1202.168498728705


In [ ]:
# Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1)
# such that each element is the following function applied on each element of A.
# f(x)=1 / (1 + exp(-x))

In [14]:
import math
def func(x):
    return 1/(1+ math.exp(-x))

In [15]:
S = np.random.rand(10,1)
print(S)

[[0.83783035]
 [0.73874103]
 [0.9894624 ]
 [0.68113074]
 [0.55311725]
 [0.85190441]
 [0.73337171]
 [0.24339183]
 [0.40347505]
 [0.73858046]]


In [16]:
print(list(map(func,S)))

[0.6980080667889714, 0.6767204925963246, 0.7289817222489081, 0.6639910192760786, 0.6348585144756561, 0.7009664832589932, 0.675544734964078, 0.5605493416479933, 0.5995222899875711, 0.6766853646234812]
